language: node_js
deploy:
  provider: npm
  email: gisli.konrad@gmail.com
  api_key:
    secure: JK2c/mHxQJAnuDulOajF/Jn7uplJ3v8DuJ3cwNTb+fbS02UC0Xkjv9/oxMHDJNNvw8/HHP3jwodbHGHY4216zInxzLr8G7j8C+3dbs8R9Ia06h4vtIlhON375NVT6zz+jiKMvXLw06MtZDDiaYu20DteWBo9e3h/hONspdCNjD3wgnOBBZTHgbcT9hwdMdGzEOgyANf0TFChX62uwRO0K/PZSXnrMpd9XLWM0r2HXxWn3kOJ0hb4cYmOu8r8gEFJ0R/xWJVJduU7aEpiU6xOJMyLcnwJrd4nZuDRff298YFNk2lktwm/4OY6XOavGpS+1be4cy+uiwDBSwj5OY+wWRJKmwoVuxf1dIu8F51uLoZm1OTW/irX4V4JQK0YydIQGVSVLtTI4Q3XbTrmTAGYFFeaL27kY41Fb/JKitwmsnPiNGOoHHQuFua8xY74acP6ubw+89WzgoE2Lp7CtoJZif+BdIUQ5JLloRYu2/4dfeuub9ZT8KjUSVJ9aSjzMWrGTt5zUV66Q2FffC8yYQM+77z3vpl6iIkC4aunz/ggz4hACzypz5RBXgG7oP9tJFjuVfz+zj+LcdCxDqO4h60S8vS6TpIFKQDXt2HEnnnqfddzo6NPqvTxY16alkSkd6NL0SnR/GWjaXx8oDPHGDdE6YJdZhtuM+avjcR1YX7SYr4=
